### ISSUE TITLE
Error: attept to write to not existing history file

### ISSUE THREAD

**Issue by 39555** [reubeno/brush#149]
Here:
https://github.com/reubeno/brush/blob/main/brush-interactive/src/interactive_shell.rs#L137
If a parent directory not found. Brush can't create a history file and exits with a non informative error:
```
ERROR error: input error: No such file or directory (os error 2)
``` 
In my case it is `/Users/ig/.local/state/bash/history`

**Comment by reubeno** [comment]
Agreed. Sounds like this should definitely be a non-fatal error (or perhaps quieter warning) instead.

I know there are some outstanding TODOs related to history file management, in general. I don't recall offhand if we're honoring the standard configuration options/variables to customize where the history file is stored, whether it's written or appended to, etc.

**Comment by reubeno** [comment]
It looks like `bash` does as I suggested earlier -- swallows the error without creating/appending to the history file. I'm proposing a change to do this (see PR link above).
