### ISSUE TITLE
heredoc doesn't work inside of command substituiton

### ISSUE THREAD

**Issue by Quackdoc** [reubeno/brush#234]
example bash:

```sh
#!/bin/sh

test1=$(cat <<EOF
test
test test
test test test
EOF
)
test2=$(echo test 2)
echo $test1
echo $test2
cat <<TEST3
test 3
TEST3

```

command output
```ps
➜  xe git:(master) ✗ bash test.sh
test test test test test test
test 2
test 3
➜  xe git:(master) ✗ brush test.sh
ERROR main: unterminated here document sequence; tag(s) found at: [line 1 col 14] (detected near line 5 column 1)

test 2
test 3
```

**Comment by 39555** [comment]
@reubeno seems like it gets tokenized twice? 
```
$(<<EOF
test
EOF
)
```
after the `tokenize_str` 
```
Word(
        "$(<<EOFtest\n\n)", //  <-- the input inside qoutes already processed by the tokenizer, but it sends it to the subshell as a raw string
        TokenLocation {
            start: SourcePosition {
                index: 0,
                line: 1,
                column: 1,
            },
            end: SourcePosition {
                index: 18,
                line: 4,
                column: 2,
            },
        },
    ),
    Operator(
        "\n",
        TokenLocation {
            start: SourcePosition {
                index: 18,
                line: 4,
                column: 2,
            },
            end: SourcePosition {
                index: 19,
                line: 5,
                column: 1,
            },
        },
    ),
]
```

**Comment by reubeno** [comment]
@39555 Yes. It's not ideal, but for the initial implementation we landed on the tokenizer yielding the full text of the command substitution in the word token that contains it (potentially along with other text, substitutions, etc.). The recursion was added to ensure that we can find the end of the substitution, but that's really all it's needed for here.

I recall having explored alternative options (e.g., support a `Word` storing a tree of sub-tokens) but selected this approach as the most practical to start with.

At this point, the proximate error seems to be that the newline between `EOF` and `test` gets lost in the mix.

**Comment by 39555** [comment]
@reubeno when the tokenizer processes the input, it replaces the last EOF with a newline for simplicity. Maybe because of that the subshell's tokenizer throws an error that the 'Here' is not closed? The first tokenizer should skip all the text inside the substitution unchanged.

**Comment by reubeno** [comment]
Good question. I added a quick test case to cover this (and improved the error):

https://github.com/reubeno/brush/commit/a290a0dd86e8c5d3b24b81ca57934c1cc7381154#diff-bf47c71a8ce1b403511f60305d7d562506a83cacb1380deefc9290960e6c7651R43

Here's what displays:

![image](https://github.com/user-attachments/assets/cb34c2ac-4dd9-417f-8ada-68a28c44c8cd)

It _appears_ that the here tag ends up getting considered as `EOF1`, with the newline between `EOF` and the first line of the here-doc body getting lost.

@39555 -- I totally understand if not, but if you happen to have time and interest to look deeper and identify a resolution, you're welcome to pick this up. Note also a few additional tests I added to `tokenizer.rs` in the linked commit (but left commented out for now). I'm not 100% certain that the assertions in it are correct but I believe they're problematic as well.

**Comment by 39555** [comment]
@reubeno Can you help me? What is that supposed to do https://github.com/reubeno/brush/blob/a7d77ffb7295600c8c17f9f3317a004f9a586ded/brush-parser/src/tokenizer.rs#L561C1-L561C47 when I place `dbg!` it is always None...

**Comment by reubeno** [comment]
@39555 Are you asking about the `strip_suffix()` call? That's where we actually check for finding the tag that should delimit the here document. If I recall correctly, it's the one place where we check to see if we've reached the terminating tag for the here document -- and then strip it off to get the actual body.

I'm not sure why you'd only ever see `None`. Are you testing with a simple case (outside a command substitution)?

(Aside: the parsing of here documents got a bit complicated in the tokenizer. Definitely open to seeing improvements to the clarity and simplicity of the implementation.)
