### ISSUE TITLE
cat command not found, shell dont run

### ISSUE THREAD

**Issue by commitcompanion** [reubeno/brush#269]
Hello!
There was an issue starting the shell. In perspective of the shell, the cat command was not found:
```
~/workbench/userlandproject 
❯ brush
/usr/bin/cat: '': Datei oder Verzeichnis nicht gefunden
~/workbench/userlandproject 
❯ ls /usr/bin/cat*
/usr/bin/cat  /usr/bin/catdoc  /usr/bin/catman  /usr/bin/catppt
~/workbench/userlandproject 
❯ 
```
Is the shell now running? or is it the previous shell.
Thank!

**Comment by reubeno** [comment]
Hi @commitcompanion -- thanks for your interest in brush! I see you filed an issue and then later closed it; were you able to resolve or otherwise sort out the error you were seeing?

**Comment by commitcompanion** [comment]
Thank you for your patience. The issue seems to be that the command was indeed running, but this was not visible because it was using the same Starship prompt automatically. For some reason, it is searching for the cat command, even though cat is present and functional:

```
~
❯ brush #it starts brush!
/usr/bin/cat: '': No such file or directory
~
❯ cat
^C
~
❯ cat .bashrc
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc
. "$HOME/.cargo/env"
eval "$(starship init bash)"
~
❯
```

so it was working!

Thanks!
